### ISSUE TITLE
It seems that the values for the 'width' and 'height' arguments are in the opposite order.

### ISSUE THREAD

**Issue by sun5066** [AgoraIO/FaceUnity#77]
https://github.com/AgoraIO/FaceUnity/blob/0e1ae5516024ee08ed4fbd8ef65d13778859b4a1/Agora-Video-With-FaceUnity-Android/app/src/main/java/io/agora/framework/PreprocessorFaceUnity.java#L197

**Comment by xgfd3** [comment]
It actually works because the rotation angle is 90 or 270, but the logic is not clear.You can refer to another example below for clearer integration steps.

https://github.com/AgoraIO/API-Examples/blob/main/Android/APIExample/app/src/main/java/io/agora/api/example/examples/advanced/beauty/FaceUnityBeauty.java
